CREATE OR REPLACE VIEW WORDLE.BEST_GUESS AS
SELECT
	GUESS,
	SUM(COUNT)
FROM
	(
		SELECT DISTINCT
			GUESS,
			G.LETTER,
			COUNT
		FROM
			GUESSES_UNPIVOT_VIEW G
			JOIN WORDLE.REMAINING_COUNTS_FILTERED_VIEW R ON (UPPER(G.LETTER) = UPPER(R.LETTER))
	)
GROUP BY
	GUESS
ORDER BY
	SUM(COUNT) DESC;
