CREATE OR REPLACE VIEW WORDLE.BEST_GUESS_SMART AS
SELECT
	GUESS,
	SUM(VALUE)
FROM
	(
		SELECT DISTINCT
			GUESS,
			G.LETTER,
			VALUE
		FROM
			wordle.GUESSES_UNPIVOT_VIEW G
			JOIN WORDLE.REMAINING_COUNTS_SMART_VIEW R ON (UPPER(G.LETTER) = UPPER(R.LETTER))
	)
GROUP BY
	GUESS
ORDER BY
	SUM(VALUE) DESC;
