CREATE OR REPLACE VIEW WORDLE.REMAINING_COUNTS_SMART_VIEW AS
SELECT
	R.LETTER as LETTER,
	CASE
		--not used yet full value
		WHEN G.LETTER IS NULL
		AND Y.LETTER IS NULL
		AND B.LETTER IS NULL THEN COUNT(*)
		--yellow but not green partial value
		WHEN Y.LETTER IS NOT NULL THEN COUNT(*) * 0.01
		--green no value
		WHEN G.LETTER IS NOT NULL THEN 0
		--grey no value
		WHEN B.LETTER IS NOT NULL THEN 0
	END AS VALUE
FROM
	WORDLE.REMAINING_UNPIVOT_VIEW R
	LEFT JOIN WORDLE.GREEN G ON (UPPER(R.LETTER) = UPPER(G.LETTER))
	LEFT JOIN WORDLE.YELLOW Y ON (UPPER(R.LETTER) = UPPER(Y.LETTER))
	LEFT JOIN WORDLE.GREY B ON (UPPER(R.LETTER) = UPPER(B.LETTER))
GROUP BY
	R.LETTER,
	G.LETTER,
	Y.LETTER,
	B.LETTER
ORDER BY
	VALUE DESC;
