CREATE OR REPLACE VIEW WORDLE.REMAINING_UNPIVOT_VIEW AS
SELECT
	answers,
	GS.POS,
	LETTERS[GS.POS] AS LETTER
FROM
	(
		SELECT
			answers,
			ARRAY[p1, p2, p3, p4, p5] AS LETTERS
		FROM
			wordle.remaining_answers
	) T
	CROSS JOIN LATERAL GENERATE_SUBSCRIPTS(T.LETTERS, 1) AS GS (POS)
ORDER BY
	answers,
	POS;

--drop view WORDLE.REMAINING_COUNTS_FILTERED_VIEW;
CREATE OR REPLACE VIEW WORDLE.REMAINING_COUNTS_FILTERED_VIEW AS
SELECT
	UPPER(LETTER) as LETTER,
	COUNT(*)
FROM
	WORDLE.REMAINING_UNPIVOT_VIEW
WHERE
	UPPER(LETTER) NOT IN (
		SELECT
			UPPER(LETTER)
		FROM
			WORDLE.YELLOW
	)
	AND UPPER(LETTER) NOT IN (
		SELECT
			UPPER(LETTER)
		FROM
			WORDLE.GREEN
	)
GROUP BY
	UPPER(LETTER)
ORDER BY
	COUNT(*) DESC;


--drop view WORDLE.REMAINING_COUNTS_UNFILTERED_VIEW;
CREATE OR REPLACE VIEW WORDLE.REMAINING_COUNTS_UNFILTERED_VIEW AS
SELECT
	UPPER(LETTER) AS LETTER,
	COUNT(*)
FROM
	WORDLE.REMAINING_UNPIVOT_VIEW
GROUP BY
	UPPER(LETTER)
ORDER BY
	COUNT(*) DESC;
